# A Jekyll template for a simple workshop website, designed for github-pages,
# based on Minima theme https://github.com/jekyll/minima

# Notes:
# - fig include, {% include figure.html file="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}
# - pages with "nav: true" in front matter will be in header nav
# - use environment variable on build command to include analytics: JEKYLL_ENV=production jekyll build

# site settings
title: Nicholas Wogan
# description: "Research Portfolio"
# keywords: "github, github-pages, websites, static gen, hosting, html, workshop, gh-pages"

# author settings for cc-by
# author: Nicholas Wogan
# pub_year: 2020
github_username: nicholaswogan

# add the full url for the github repository
repo: "https://github.com/Nicholaswogan/Nicholaswogan.github.io"

# urls
# your gh-pages url: https://username.github.io
# url: https://nicholaswogan.github.io/
# your repository name: /repository
# baseurl:

# analytics if desired (and use environment variable on build command)
# google_analytics: UA-74844011-1

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

  - scope:
      path: ""
      type: pages
    values:
      layout: default_1

# Build settings
markdown: kramdown
